server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/onsucjuk/SpringConfigFile2
          default-label: master
          search-paths: msa